#define VIDEO_XPOS 46
#define VIDEO_YPOS 53

#define IMAGE_WIDTH 708
#define IMAGE_HEIGHT 404

#define IMG_BUTTON_WIDTH 86
#define IMG_BUTTON_YPOS 323
#define IMG_BUTTON_INDICATOR_YPOS 363

#define BUTTON_RGB_XPOS 41
#define BUTTON_HSV_XPOS 162
#define BUTTON_TRACK_XPOS 283
#define BUTTON_INDICATOR_HEIGHT 14

#define BUTTON_WIDTH 118
#define BUTTON_HEIGHT 40

#define BUTTON_COL_1_XPOS 406
#define BUTTON_COL_2_XPOS 549

#define BUTTON_MAN_YPOS 49
#define BUTTON_AUT_YPOS 134
#define BUTTON_RECONNECT_YPOS 197
#define BUTTON_EXIT_YPOS 260
#define BUTTON_SHUTDOWN_YPOS 323

#define STATUS_SIDE 25
#define STATUS_XPOS 665
#define STATUS_YPOS 15

#define CONTROLLER_YPOS 51

#define SENSITIVITY_YPOS 260
#define SENSITIVITY_DWN_BTN_XPOS 468
#define SENSITIVITY_BTN_HEIGHT 40
#define SENSITIVITY_BTN_WIDTH 57
